; PlatformIO Project Configuration File
;
; Build and upload:
;   pio run -e uno_r4_wifi           --target upload
;   pio run -e esp32dev              --target upload
;   pio run -e esp32c6_waveshare_lcd --target upload
;   pio run -e esp32cam              --target upload

[env]
monitor_speed = 115200

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/uno_r4_wifi
    -DAPP_VERSION=\"1.2\"
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/esp32dev
    -DAPP_VERSION=\"1.2\"
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/esp32cam
    -DAPP_VERSION=\"1.2\"
    -DESP32CAM=1
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

[env:esp32c6_waveshare_lcd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-c6-devkitc-1
board_build.flash_mode = dio
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/esp32c6_waveshare_lcd
    -DAPP_VERSION=\"1.2\"
    -DWAVESHARE_ESP32C6_LCD=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    bblanchon/ArduinoJson
    moononournation/GFX Library for Arduino
